// generated by http://www.jsonschema2pojo.org/
package com.myq.interview.cleaner.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "map",
        "start",
        "commands",
        "battery"
})
public class Input {

    @JsonProperty("map")
    private Character[][] map = null;
    @JsonProperty("start")
    private RobotPosition start;
    @JsonProperty("commands")
    private String[] commands = null;
    @JsonProperty("battery")
    private Integer battery;

    /**
     * No args constructor for use in serialization
     *
     */
    public Input() {
    }

    /**
     *
     * @param start
     * @param battery
     * @param map
     * @param commands
     */
    public Input(Character[][] map, RobotPosition start, String[] commands, Integer battery) {
        super();
        this.map = map;
        this.start = start;
        this.commands = commands;
        this.battery = battery;
    }

    @JsonProperty("map")
    public Character[][] getMap() {
        return map;
    }

    @JsonProperty("map")
    public void setMap(Character[][] map) {
        this.map = map;
    }

    @JsonProperty("start")
    public RobotPosition getStart() {
        return start;
    }

    @JsonProperty("start")
    public void setStart(RobotPosition start) {
        this.start = start;
    }

    @JsonProperty("commands")
    public String[] getCommands() {
        return commands;
    }

    @JsonProperty("commands")
    public void setCommands(String[] commands) {
        this.commands = commands;
    }

    @JsonProperty("battery")
    public Integer getBattery() {
        return battery;
    }

    @JsonProperty("battery")
    public void setBattery(Integer battery) {
        this.battery = battery;
    }

}