// generated by http://www.jsonschema2pojo.org/
package com.myq.interview.cleaner.data;

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "visited",
        "cleaned",
        "final",
        "battery"
})
public class Output {

    @JsonProperty("visited")
    private Set<Position> visited = null;
    @JsonProperty("cleaned")
    private Set<Position> cleaned = null;
    @JsonProperty("final")
    private RobotPosition _final;
    @JsonProperty("battery")
    private int battery;

    /**
     * No args constructor for use in serialization
     *
     */
    public Output() {
    }

    /**
     *
     * @param visited
     * @param cleaned
     * @param _final
     * @param battery
     */
    public Output(Set<Position> visited, Set<Position> cleaned, RobotPosition _final, int battery) {
        super();
        this.visited = visited;
        this.cleaned = cleaned;
        this._final = _final;
        this.battery = battery;
    }

    @JsonProperty("visited")
    public Set<Position> getVisited() {
        return visited;
    }

    @JsonProperty("visited")
    public void setVisited(Set<Position> visited) {
        this.visited = visited;
    }

    @JsonProperty("cleaned")
    public Set<Position> getCleaned() {
        return cleaned;
    }

    @JsonProperty("cleaned")
    public void setCleaned(Set<Position> cleaned) {
        this.cleaned = cleaned;
    }

    @JsonProperty("final")
    public RobotPosition getFinal() {
        return _final;
    }

    @JsonProperty("final")
    public void setFinal(RobotPosition _final) {
        this._final = _final;
    }

    @JsonProperty("battery")
    public int getBattery() {
        return battery;
    }

    @JsonProperty("battery")
    public void setBattery(int battery) {
        this.battery = battery;
    }
}