// generated by http://www.jsonschema2pojo.org/
package com.myq.interview.cleaner.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "X",
        "Y",
        "facing"
})
public class RobotPosition extends Position {

    @JsonProperty("facing")
    private String facing;

    /**
     * No args constructor for use in serialization
     *
     */
    public RobotPosition() {
    }

    /**
     *
     * @param x
     * @param y
     * @param facing
     */
    public RobotPosition(Integer x, Integer y, String facing) {
        super(x, y);
        this.facing = facing;
    }

    @JsonProperty("facing")
    public String getFacing() {
        return facing;
    }

    @JsonProperty("facing")
    public void setFacing(String facing) {
        this.facing = facing;
    }

}